name: Compile and Test crispy

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [develop]

env:
  GO111MODULE: "on"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: [1.16, 1.17]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}

      - name: Get go tools
        run: |
          go install mvdan.cc/gofumpt@latest

      - name: Get deps
        run: go mod download

      - name: Format
        run: gofumpt -w .

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
          github-token: ${{ github.token }}

      - name: Test
        run: go test -v ./...
